### ISSUE TITLE
Doesn't work with coroutines 1.0.0-RC1 

### ISSUE THREAD

**Issue by antanas-arvasevicius** [ktorio/ktor#668]
Hi, we've just updated to coroutines 1.0.0-RC1, tested with ktor 1.0.0-beta-1 and getting an error:
Would be possible to release another beta-1-coroutines100 with coroutines 1.0.0 support?

````
Exception in thread "main" java.lang.NoSuchMethodError: kotlinx.coroutines.ExecutorsKt.asCoroutineDispatcher(Ljava/util/concurrent/ExecutorService;)Lkotlinx/coroutines/ExecutorCoroutineDispatcher;
	at io.ktor.server.netty.NettyApplicationEngine.<init>(NettyApplicationEngine.kt:73)
	at io.ktor.server.netty.DevelopmentEngine.main(DevelopmentEngine.kt:17)
````

**Comment by antanas-arvasevicius** [comment]
For now I've used jitpack to use 1.0.0-RC1

```
    ext.ktor_version = 'master-SNAPSHOT'
    repositories {
//...
        maven { url 'https://jitpack.io' }
    }
    dependencies { 
        testImplementation("com.github.ktorio.ktor:ktor-server-test-host:$ktor_version") {
            exclude group: 'com.github.ktorio.ktor'
        }
       implementation("com.github.ktorio.ktor:ktor-server-core:$ktor_version")
    }
```

**Comment by cy6erGn0m** [comment]
1.0.0-beta-2 is compatible with 1.0.0-RC1
