### PR TITLE
KTOR-2600 Update Kotlin and libraries to 1.5.0

### PR DESCRIPTION
**Pull request by e5l**
Fix [KTOR-2600](https://youtrack.jetbrains.com/issue/KTOR-2600)

### CODE REVIEW

**Review by kris87us — APPROVED** [review]

**Comment by hfhbd** [comment]
Do you want to handle deprecation warnings in a separate PR?

**Comment by e5l** [comment]
I want to fix native errors first, current PR is blocked by https://github.com/Kotlin/kotlinx.coroutines/issues/2686

**Comment by e5l** [comment]
We're making the release at the end of each month, it will be till the end of this week

**Comment by jorgezim** [comment]
awesome, thanks for the quick reply

**Comment by jorgezim** [comment]
Hello again, I am using the latest release 1.6 with kotlinx.coroutines 1.5.0 and I am getting this error:

e: Compilation failed: Deserializer for declaration public kotlinx.coroutines/cancel|-8901161077954086727[0] is not found

 * Source files: 
 * Compiler version info: Konan: 1.5 / Kotlin: 1.5.0
 * Output kind: STATIC_CACHE


Everything works ok with ktor 1.5.4 and coroutines 1.4..3-native-mt

**Comment by hfhbd** [comment]
Could you try it again with Kotlin 1.5.10?

**Comment by Stexxe** [comment]
@jorgezim please file a separate issue [here](https://youtrack.jetbrains.com/newIssue?project=KTOR).

**Comment by jorgezim** [comment]
Nothing still same error using Kotlin 1.5.10. I already log a ticket https://youtrack.jetbrains.com/issue/KTOR-2755
This is a big blocker for me.
