### ISSUE TITLE
Ktor ssl websocket doesn't work on Android

### ISSUE THREAD

**Issue by antanas-arvasevicius** [ktorio/ktor#732]
Hi, I've used latest ktor on android, but got exception when used ssl websocket.

```kotlin
    private val client = HttpClient(CIO).config {
        install(WebSockets)
    }
   client.wss(host = uri.host, port = uri.port, path = uri.encodedPath) { process(this) }
   
```

```
Fatal Exception: java.lang.NoSuchMethodError
No static method getInstanceStrong()Ljava/security/SecureRandom; in class Ljava/security/SecureRandom; or its super classes (declaration of 'java.security.SecureRandom' appears in /system/framework/core-libart.jar)


Fatal Exception: java.lang.NoSuchMethodError: No static method getInstanceStrong()Ljava/security/SecureRandom; in class Ljava/security/SecureRandom; or its super classes (declaration of 'java.security.SecureRandom' appears in /system/framework/core-libart.jar)
       at io.ktor.client.engine.cio.CIOEngineConfigKt.<clinit>(CIOEngineConfig.kt:9)
       at io.ktor.client.engine.cio.HttpsConfig.<init>(CIOEngineConfig.kt:29)
       at io.ktor.client.engine.cio.CIOEngineConfig.<init>(CIOEngineConfig.kt:13)
       at io.ktor.client.engine.cio.CIO.create(CIO.kt:14)
       at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:27)
       at io.ktor.client.HttpClientKt.HttpClient$default(HttpClient.kt:24)
       at com.eld.common.telemetry.TelemetryService.<init>(TelemetryService.kt:97)
       at com.eld.android.ApplicationService.initialize(ApplicationService.kt:335)
       at com.eld.android.ApplicationService.start(ApplicationService.kt:452)
       at com.eld.android.ApplicationService.onStartCommand(ApplicationService.kt:435)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3014)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by e5l** [comment]
Hi, @antanas-arvasevicius. Thanks for the report, it's known issue.
Yep. There are `Android` and `OkHttp` engines dedicated for Android. 
`CIO` engine works with android Oreo(8.0) and higher.

**Comment by antanas-arvasevicius** [comment]
But as I've understood from docs, that websockets works only with CIO
right? Or other engines also could be used?
And btw simple websocket seems works correctly on older android versions or
it can be some known glitches or this just works by accident :-)

**Comment by antanas-arvasevicius** [comment]
Hi, @e5l just FYI
I'd copied all ktor client websocket feature and managed to run it on older Androids.

* in ktor.util.Crypto  decodeBase64 / encodeBase64 should not depend on java Base64 implementation, I've replaced it to ```org.apache.commons.codec.binary.Base64```
* replaced java native Duration to data class Duration, which was used in DefaultWebSocketSession, DefaultWebSocketSessionImpl, PingPong (pinger / ponger).
```kotiln
data class Duration(private val millis: Long) {
    companion object {
        fun ofSeconds(seconds: Int): Duration = Duration(seconds * 1000L)
        fun ofMinutes(minutes: Int): Duration = Duration(minutes * 60 * 1000L)
    }
    fun toMillis() = millis
}
```
And that`s all. Seems like is not worth to use any classes which is in java.* package :)

**Comment by e5l** [comment]
Hi, @antanas-arvasevicius. 
Could you make a PR? :)

**Comment by antanas-arvasevicius** [comment]
I will try to submit PR. Currently I've only hard copied sources of ktor-client/ktor-client-features/ktor-client-websocket and made changes.

**Comment by antanas-arvasevicius** [comment]
Hi, @e5l. Unfortunately I'm still getting errors on Android 6.0 and cannot figure out why, maybe, do you have any clues what could cause this? Compiled debug variant with proguard disabled.

```kotlin
Fatal Exception: java.lang.NoClassDefFoundErrorio.ktor.client.engine.cio.CIOEngine$executeRequest$$inlined$with$lambda$1
--
  | io.ktor.client.engine.cio.CIOEngine.executeRequest (CIOEngine.kt:34)
  | io.ktor.client.engine.cio.CIOEngine.execute (CIOEngine.kt:23)
  | io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.invokeSuspend (HttpClient.kt:74)
  | io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.invoke (HttpClient.kt)
  | io.ktor.util.pipeline.SuspendFunctionGun.loop (PipelineContext.kt:248)
  | io.ktor.util.pipeline.SuspendFunctionGun.access$loop (PipelineContext.kt:63)
  | io.ktor.util.pipeline.SuspendFunctionGun.proceed (PipelineContext.kt:111)
  | io.ktor.util.pipeline.SuspendFunctionGun.execute (PipelineContext.kt:131)
  | io.ktor.util.pipeline.Pipeline.execute (Pipeline.kt:24)
  | io.ktor.client.features.HttpSend$DefaultSender.execute (HttpSend.kt:86)
  | io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend (HttpSend.kt:58)
  | io.ktor.client.features.HttpSend$Feature$install$1.invoke (HttpSend.kt)
  | io.ktor.util.pipeline.SuspendFunctionGun.loop (PipelineContext.kt:248)
  | io.ktor.util.pipeline.SuspendFunctionGun.access$loop (PipelineContext.kt:63)
  | io.ktor.util.pipeline.SuspendFunctionGun.proceed (PipelineContext.kt:111)
  | io.ktor.util.pipeline.SuspendFunctionGun.proceedWith (PipelineContext.kt:121)
  | com.eld.common.ktor.websocket.WebSockets$Feature$install$1.invokeSuspend (WebSockets.kt:38)
```

Code on 34 line of CIOEngine.kt is:
```kotlin
    private suspend fun executeRequest(request: DefaultHttpRequest): CIOHttpResponse {
        while (true) {
            if (closed.get()) throw ClientClosedException()

            val endpoint = with(request.url) {
                val address = "$host:$port:$protocol"
                endpoints.computeIfAbsent(address) { // <-- 34 line here
                    val secure = (protocol.isSecure())
                    Endpoint(
                        host, port, secure,
                        config,
                        connectionFactory, coroutineContext,
                        createCallContext = { createCallContext() }, onDone = { endpoints.remove(address) }
                    )
                }
            }

            try {
                return endpoint.execute(request)
            } catch (cause: ClosedSendChannelException) {
                if (closed.get()) throw ClientClosedException(cause)
                continue
            } finally {
                if (closed.get()) endpoint.close()
            }
        }
    }
```

**Comment by e5l** [comment]
The `computeIfAbsent` method was added in API level 24

**Comment by antanas-arvasevicius** [comment]
I think this is a main problem: "or due missing java.util.function.Function in android 6 - luontola/retrolambda#126 (comment)"  retrolambda or  Android Studio 3+ compatibility should fix this, I'm trying to experiment with that.

**Comment by e5l** [comment]
You could also try to build it with `android.enableR8 = true`

**Comment by antanas-arvasevicius** [comment]
Had no luck at fixing this... seems that older androids do not support java 8 API calls at all, and computeIfAbsent is one of them.

Maybe related: https://stackoverflow.com/questions/42869086/java-lang-noclassdeffounderror-inlinedforeachlambda1-in-kotlin?noredirect=1&lq=1

**Comment by antanas-arvasevicius** [comment]
According to https://developer.android.com/studio/write/java8-support 
java.util.function  is available only when targeting API level 24 or higher. (android 7.0+)
and ```computeIfAbsent``` uses ```java.util.function.Function``` looks like dead end, and ktor websockets can be supported only on Android 7.0+ (if decoupled from base64 and java Duration)

**Comment by avently** [comment]
@antanas-arvasevicius Hello. 

> java.util.function is available only when targeting API level 24 or higher. (android 7.0+)
> and `computeIfAbsent` uses `java.util.function.Function` looks like dead end, and ktor websockets can be supported only on Android 7.0+ (if decoupled from base64 and java Duration)

Issue with computeIfAbsent was fixed by @cy6erGn0m. Thanks him for that.
see: https://github.com/ktorio/ktor/commit/7f43b6243f5a9a306e06a383f476957fdc7b35af#diff-5f8974923ee2f59d21dbfc7cf6776187

Can you make a PR with your other changes? Maybe it will work as expected then

**Comment by luca992** [comment]
@antanas-arvasevicius did you get a chance to try @avently's suggestion?

**Comment by antanas-arvasevicius** [comment]
I can confirm that now it works on Android 6.0+ but I've copied all websocket client into my project and replaced Base64 encodings to apache common.
1)
```kotlin
packageproject.common.ktor.websocket
import org.apache.commons.codec.binary.Base64
fun websocketServerAccept(nonce: String): String = String(Base64.encodeBase64((sha1("${nonce.trim()}$WebSocketServerAcceptTail".toByteArray(Charsets.ISO_8859_1))))
```
2)
```kotlin
package com.eld.common.ktor.websocket
class WebSocketContent : ClientUpgradeContent() {

    private val nonce: String = buildString {
        val bytes = ByteArray(NONCE_SIZE)
        random.nextBytes(bytes)
        append(String(Base64.encodeBase64(bytes)))
    }
```

Actually I've seen that ktor itself has multiplatform base64 encoding/decoding, but cannot understand why they do not use that for websocket client.

Here is: https://github.com/ktorio/ktor/blob/712e6119564c7cfb58529c9aaf64c554f1211a58/ktor-utils/common/src/io/ktor/util/Base64.kt

It's only needed to have `fun ByteArray.encodeBase64(): String` and use that instead of JVM specific implementation. 

By writing this I've found that actually this function was added to ktor: https://github.com/ktorio/ktor/commit/e8de451d76c22e4466a5692975acfcc3edf17d4f

But not published yet. So it's probably with 1.1.4 we'll finally have multiplatform websockets :)

**Comment by luca992** [comment]
@antanas-arvasevicius I made some changes and I can verify websocket is working down to Android API level 21... (Maybe even lower, but haven't tested) 

made a pull request. https://github.com/ktorio/ktor/pull/999

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-722">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Should be fixed in Ktor 1.4.0
