### ISSUE TITLE
Ktor with kotlin v1.3.20-eap-52

### ISSUE THREAD

**Issue by webfrea-k** [ktorio/ktor#848]
Any plans to release a version working with Kotlin v1.3.20-eap-52?
I'm having some issues with following dependencies when building for iOS (using version 1.0.1)
```
ktor_version_ios=1.0.1
implementation "io.ktor:ktor-client-core-ios:$ktor_version_ios"
implementation "io.ktor:ktor-client-ios:$ktor_version_ios"
implementation "io.ktor:ktor-client-json-ios:$ktor_version_ios"
```
Error:
```
error: compilation failed: Could not find "/Users/x/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-client-ios_debug_ios_x64/1.0.1/7ac4ac71743dbff041cc51a117e1732a9133d3b8/ktor-client-ios.klib" in [/Users/x/Projects/mobile-sdk-kotlin-native/shared, /Users/x/.konan/klib, /Users/x/.konan/kotlin-native-macos-1.1-rc2-5323/klib/common, /Users/x/.konan/kotlin-native-macos-1.1-rc2-5323/klib/platform/ios_x64].

 * Source files: *******
 * Compiler version info: Konan: 1.1-rc2-5323 / Kotlin: 1.3.20
 * Output kind: FRAMEWORK

exception: java.lang.IllegalStateException: Could not find "/Users/x/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-client-ios_debug_ios_x64/1.0.1/7ac4ac71743dbff041cc51a117e1732a9133d3b8/ktor-client-ios.klib" in [/Users/x/Projects/mobile-sdk-kotlin-native/shared, /Users/x/.konan/klib, /Users/x/.konan/kotlin-native-macos-1.1-rc2-5323/klib/common, /Users/x/.konan/kotlin-native-macos-1.1-rc2-5323/klib/platform/ios_x64].
	at org.jetbrains.kotlin.konan.library.KonanLibraryProperResolver.resolve(SearchPathResolver.kt:194)
```

**Comment by webfrea-k** [comment]
Ok thanks.
If I understand correctly, I need to wait for version `eap-59` or higher (depending on `KT-29004`), and also all my other libraries must be compatible with that `eap-59 `or higher?

**Comment by cy6erGn0m** [comment]
Yes, exactly. The next EAP is coming soon

**Comment by webfrea-k** [comment]
Ok. Thanks for clarification 👍

**Comment by joreilly** [comment]
Was this resolved?  Still seeing issue with v1.3.20-eap-100 but might tripping up on "all my other libraries must be compatible with that"...how do you know what versions other libraries should be?

**Comment by webfrea-k** [comment]
@joreilly just try to find the last ones. I usually check repository urls, for existing (newest) versions, and  try them out. [Link](https://dl.bintray.com/kotlin/ktor/io/ktor/ktor-client-core-ios/): Here you can see, that the last one is 1.0.1 (same as in my original post). Until Ktor greater than 1.0.1 is created, it wont work. Except if there is any eap ktor repo link available?

**Comment by joreilly** [comment]
Thanks @webfrea-k , I'll keep on eye on that link
